services:
  django:
    build: .
    container_name: django
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./src:/usr/src/app
      - ./src/media:/usr/src/app/media
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - pgdb
      - redis
    stdin_open: true
    tty: true

  celery:
    build: .
    container_name: celery
    command: celery -A config worker -l INFO
    volumes:
      - ./src:/usr/src/app
    env_file:
      - .env
    depends_on:
      - django
      - redis

  celery_beat:
    build: .
    container_name: celery_beat
    command: celery -A config beat -l INFO --pidfile=
    volumes:
      - ./src:/usr/src/app
    env_file:
      - .env
    depends_on:
      - django
      - redis

  pgdb:
    image: postgres:14
    container_name: pgdb
    environment:
      - POSTGRES_DB=${PG_DATABASE}
      - POSTGRES_USER=${PG_USER}
      - POSTGRES_PASSWORD=${PG_PASSWORD}
    volumes:
      - pgdata:/var/lib/postgresql/data/

  redis:
    image: "redis:alpine"

volumes:
  pgdata:
